name: Build the Program

on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # version: ['latest', 'beta', '1.18.0']
        version: ['1.18.0']
    steps:
      # - uses: actions/checkout@v4
      - name: Install Solana CLI
        uses: nickfrosty/github-actions/install-solana@v1.1.3
        with:
          version: ${{ matrix.version }}
      - name: Build Program
        run: solana-test-validator --version